### PR TITLE
Support async-profiler 2.x

### PR DESCRIPTION
**Pull request by retronym**
Allow multiple events to be captured simultaneously in this version,
given that JFR is chosen as output format.

Delegate output file writing to the async-profiler. This is required
in 2.x for the JFR output but is supported in both versions. The file
path must be provided when starting the profiler with JFR output, so
we need to create the per-trial output directory in the first
`beforeIteration`.

Avoid the character '%' in the generated directory name as this
is interpreted by async-profiler as part %p or %t placeholder.

### CODE REVIEW

**Comment by retronym** [comment]
Heads up @shipilev @apangin, I'm working on support for async-profiler 2.x in the JMH integration. I'll submit the patch next week.

**Comment by shipilev** [comment]
See https://github.com/openjdk/jmh/commit/2415f72d50335a927749c36d730c4e05ad1626e1 -- I think we better to have `1.x` compatibility for a while longer.

**Comment by retronym** [comment]
Thanks. I'll aim for cross compatibility as much as possible.

**Comment by retronym** [comment]
```
➜  compiler-benchmark git:(master) ✗ (export ASYNC_PROFILER_DIR=/Users/jz/code/async-profiler; sbt 'profAsyncCpu hot -psource=scalap -f1 -wi 1 -i 1')
[info] welcome to sbt 1.4.9 (AdoptOpenJDK Java 1.8.0_272)
[info] loading global plugins from /Users/jz/.sbt/1.0/plugins
[info] loading settings for project compiler-benchmark-build from build.sbt,plugins.sbt ...
[info] loading project definition from /Users/jz/code/compiler-benchmark/project
[info] loading settings for project compiler-benchmark from build.sbt ...
[info] set current project to compiler-benchmark (in build file:/Users/jz/code/compiler-benchmark/)
-prof "async:dir=/Users/jz/code/compiler-benchmark/target/profile-async-cpu;libPath=/Users/jz/code/async-profiler/build/libasyncProfiler.so;minwidth=1;width=1800;verbose=true;event=cpu;filter=false;flat=40;trace=10;framebuf=33554432;output=flamegraph,jfr,text"
[info] compiling 5 Java sources to /Users/jz/code/compiler-benchmark/infrastructure/target/classes ...
[warn] multiple main classes detected: run 'show discoveredMainClasses' to see the list
[info] compiling 4 Scala sources and 3 Java sources to /Users/jz/code/compiler-benchmark/compilation/target/scala-2.12/classes ...
[warn] /Users/jz/code/compiler-benchmark/compilation/src/main/scala/scala/tools/nsc/HotSbtBenchmark.scala:7:36: imported `Mode' is permanently hidden by definition of value Mode in package nsc
[warn] import org.openjdk.jmh.annotations.Mode
[warn]                                    ^
[warn] /Users/jz/code/compiler-benchmark/compilation/src/main/scala/scala/tools/nsc/BenchmarkUtils.scala:50:62: match may not be exhaustive.
[warn] It would fail on the following input: Nil
[warn]       val (cond, expr) = trimmedLine.split(" ").toList.filter(_.nonEmpty) match {
[warn]                                                              ^
[warn] two warnings found
[info] /Users/jz/code/compiler-benchmark/compilation/src/main/scala/scala/tools/nsc/JavacBenchmark.java: Some input files use unchecked or unsafe operations.
[info] /Users/jz/code/compiler-benchmark/compilation/src/main/scala/scala/tools/nsc/JavacBenchmark.java: Recompile with -Xlint:unchecked for details.
[info] compiling 25 Java sources to /Users/jz/code/compiler-benchmark/compilation/target/scala-2.12/classes ...
[info] running (fork) scala.bench.ScalacBenchmarkRunner HotScalacBenchmark -foe true -psource=scalap -f1 -wi 1 -i 1 -jvmArgs -Dsun.reflect.inflationThreshold=0 -prof async:dir=/Users/jz/code/compiler-benchmark/target/profile-async-cpu;libPath=/Users/jz/code/async-profiler/build/libasyncProfiler.so;minwidth=1;width=1800;verbose=true;event=cpu;filter=false;flat=40;trace=10;framebuf=33554432;output=flamegraph,jfr,text -o /Users/jz/code/compiler-benchmark/target/profile-async-cpu/jmh.log -rf json -rff /Users/jz/code/compiler-benchmark/target/profile-async-cpu/result.json
[info] [HotScalacBenchmark, -foe, true, -psource=scalap, -f1, -wi, 1, -i, 1, -jvmArgs, -Dsun.reflect.inflationThreshold=0, -prof, async:dir=/Users/jz/code/compiler-benchmark/target/profile-async-cpu;libPath=/Users/jz/code/async-profiler/build/libasyncProfiler.so;minwidth=1;width=1800;verbose=true;event=cpu;filter=false;flat=40;trace=10;framebuf=33554432;output=flamegraph,jfr,text, -o, /Users/jz/code/compiler-benchmark/target/profile-async-cpu/jmh.log, -rf, json, -rff, /Users/jz/code/compiler-benchmark/target/profile-async-cpu/result.json]
[info] [async-profiler] start,,event=cpu,framebuf=33554432,width=1800,minwidth=1,file=/Users/jz/code/compiler-benchmark/target/profile-async-cpu/scala.tools.nsc.HotScalacBenchmark.compile-SampleTime-corpusPath-.._2Fcorpus-corpusVersion-a8c43dc-extraArgs--resident-false-scalaVersion-2.12.12-source-scalap/profile.jfr
[info] [async-profiler] stop
[info] [async-profiler] start,,event=cpu,framebuf=33554432,width=1800,minwidth=1,reset,file=/Users/jz/code/compiler-benchmark/target/profile-async-cpu/scala.tools.nsc.HotScalacBenchmark.compile-SampleTime-corpusPath-.._2Fcorpus-corpusVersion-a8c43dc-extraArgs--resident-false-scalaVersion-2.12.12-source-scalap/profile.jfr
[info] [async-profiler] stop
[info] [async-profiler] flamegraph,,event=cpu,framebuf=33554432,width=1800,minwidth=1,file=/Users/jz/code/compiler-benchmark/target/profile-async-cpu/scala.tools.nsc.HotScalacBenchmark.compile-SampleTime-corpusPath-.._2Fcorpus-corpusVersion-a8c43dc-extraArgs--resident-false-scalaVersion-2.12.12-source-scalap/flame-cpu-forward.html
[info] [async-profiler] flamegraph,reverse,,event=cpu,framebuf=33554432,width=1800,minwidth=1,file=/Users/jz/code/compiler-benchmark/target/profile-async-cpu/scala.tools.nsc.HotScalacBenchmark.compile-SampleTime-corpusPath-.._2Fcorpus-corpusVersion-a8c43dc-extraArgs--resident-false-scalaVersion-2.12.12-source-scalap/flame-cpu-reverse.html
[info] [async-profiler] summary,flat=40,traces=10,,event=cpu,framebuf=33554432,width=1800,minwidth=1,file=/Users/jz/code/compiler-benchmark/target/profile-async-cpu/scala.tools.nsc.HotScalacBenchmark.compile-SampleTime-corpusPath-.._2Fcorpus-corpusVersion-a8c43dc-extraArgs--resident-false-scalaVersion-2.12.12-source-scalap/summary-cpu.txt
[success] Total time: 34 s, completed 07/05/2021 3:18:55 PM
➜  compiler-benchmark git:(master) ✗ (export ASYNC_PROFILER_DIR=/Users/jz/code/async-profiler-1x; sbt 'profAsyncCpu hot -psource=scalap -f1 -wi 1 -i 1')
[info] welcome to sbt 1.4.9 (AdoptOpenJDK Java 1.8.0_272)
[info] loading global plugins from /Users/jz/.sbt/1.0/plugins
[info] loading settings for project compiler-benchmark-build from build.sbt,plugins.sbt ...
[info] loading project definition from /Users/jz/code/compiler-benchmark/project
[info] loading settings for project compiler-benchmark from build.sbt ...
[info] set current project to compiler-benchmark (in build file:/Users/jz/code/compiler-benchmark/)
-prof "async:dir=/Users/jz/code/compiler-benchmark/target/profile-async-cpu;libPath=/Users/jz/code/async-profiler-1x/build/libasyncProfiler.so;minwidth=1;width=1800;verbose=true;event=cpu;filter=false;flat=40;trace=10;framebuf=33554432;output=flamegraph,jfr,text"
[warn] multiple main classes detected: run 'show discoveredMainClasses' to see the list
[info] compiling 25 Java sources to /Users/jz/code/compiler-benchmark/compilation/target/scala-2.12/classes ...
[info] running (fork) scala.bench.ScalacBenchmarkRunner HotScalacBenchmark -foe true -psource=scalap -f1 -wi 1 -i 1 -jvmArgs -Dsun.reflect.inflationThreshold=0 -prof async:dir=/Users/jz/code/compiler-benchmark/target/profile-async-cpu;libPath=/Users/jz/code/async-profiler-1x/build/libasyncProfiler.so;minwidth=1;width=1800;verbose=true;event=cpu;filter=false;flat=40;trace=10;framebuf=33554432;output=flamegraph,jfr,text -o /Users/jz/code/compiler-benchmark/target/profile-async-cpu/jmh.log -rf json -rff /Users/jz/code/compiler-benchmark/target/profile-async-cpu/result.json
[info] [HotScalacBenchmark, -foe, true, -psource=scalap, -f1, -wi, 1, -i, 1, -jvmArgs, -Dsun.reflect.inflationThreshold=0, -prof, async:dir=/Users/jz/code/compiler-benchmark/target/profile-async-cpu;libPath=/Users/jz/code/async-profiler-1x/build/libasyncProfiler.so;minwidth=1;width=1800;verbose=true;event=cpu;filter=false;flat=40;trace=10;framebuf=33554432;output=flamegraph,jfr,text, -o, /Users/jz/code/compiler-benchmark/target/profile-async-cpu/jmh.log, -rf, json, -rff, /Users/jz/code/compiler-benchmark/target/profile-async-cpu/result.json]
[info] [async-profiler] start,,event=cpu,framebuf=33554432,width=1800,minwidth=1,file=/Users/jz/code/compiler-benchmark/target/profile-async-cpu/scala.tools.nsc.HotScalacBenchmark.compile-SampleTime-corpusPath-.._2Fcorpus-corpusVersion-a8c43dc-extraArgs--resident-false-scalaVersion-2.12.12-source-scalap/profile.jfr
[info] [async-profiler] stop
[info] [async-profiler] start,,event=cpu,framebuf=33554432,width=1800,minwidth=1,reset,file=/Users/jz/code/compiler-benchmark/target/profile-async-cpu/scala.tools.nsc.HotScalacBenchmark.compile-SampleTime-corpusPath-.._2Fcorpus-corpusVersion-a8c43dc-extraArgs--resident-false-scalaVersion-2.12.12-source-scalap/profile.jfr
[info] [async-profiler] stop
[info] [async-profiler] flamegraph,,event=cpu,framebuf=33554432,width=1800,minwidth=1,file=/Users/jz/code/compiler-benchmark/target/profile-async-cpu/scala.tools.nsc.HotScalacBenchmark.compile-SampleTime-corpusPath-.._2Fcorpus-corpusVersion-a8c43dc-extraArgs--resident-false-scalaVersion-2.12.12-source-scalap/flame-cpu-forward.svg
[info] [async-profiler] flamegraph,reverse,,event=cpu,framebuf=33554432,width=1800,minwidth=1,file=/Users/jz/code/compiler-benchmark/target/profile-async-cpu/scala.tools.nsc.HotScalacBenchmark.compile-SampleTime-corpusPath-.._2Fcorpus-corpusVersion-a8c43dc-extraArgs--resident-false-scalaVersion-2.12.12-source-scalap/flame-cpu-reverse.svg
[info] [async-profiler] summary,flat=40,traces=10,,event=cpu,framebuf=33554432,width=1800,minwidth=1,file=/Users/jz/code/compiler-benchmark/target/profile-async-cpu/scala.tools.nsc.HotScalacBenchmark.compile-SampleTime-corpusPath-.._2Fcorpus-corpusVersion-a8c43dc-extraArgs--resident-false-scalaVersion-2.12.12-source-scalap/summary-cpu.txt
[success] Total time: 27 s, completed 07/05/2021 3:20:33 PM
```

**Comment by retronym** [comment]
Submitted upstream as https://github.com/openjdk/jmh/pull/37

**Pull request closed without merging**
