### PR TITLE
Add a profiler based on async-profiler

### PR DESCRIPTION
**Pull request by retronym**
## Full set of options
```
[info] Usage: -prof <profiler-name>:opt1=value1,value2;opt2=value3
[info] Options accepted by async:
[info]   allkernel=<bool>                 only include kernel-mode events
[info]   alluser=<bool>                   only include user-mode events
[info]   ann=<bool>                       Annotate Java method names
[info]   asyncProfilerDir=<directory>     Path to build of of https://github.com/jvm-profiling-tools/async-profiler.
[info]                                    Can also be provided as an environment variable $ASYNC_PROFILER_DIR
[info]   cstack=<bool>                    how to traverse C stack
[info]   event=<>                         Event to sample: cpu, alloc, wall, lock, cache-misses
[info]                                    etc. (default: [cpu])
[info]   exclude=<regexp+>                exclude stack traces with the specified pattern
[info]   file=<file>                      Output file. '%p' and '%t' are expanded to the Process
[info]                                    ID and timestamp respectively. The output type is
[info]                                    determined by the extension, one of .collapsed (collapsed
[info]                                    stacks) / .svg (flamegraph) / .html (Tree) / .jfr
[info]                                    (Java Flight Recorder) / .txt stacks. If no file is
[info]                                    provided, the default output format is textual and
[info]                                    includes a summary, the top stacks and top methods.
[info]   flat=<int>                       Number of top flat profile to include in the default
[info]                                    output (default: [200])
[info]   framebuf=<bytes>                 Size of profiler framebuffer
[info]   help                             Display help.
[info]   include=<regexp+>                output only stack traces containing the specified
[info]                                    pattern
[info]   interval=<ns>                    Profiling interval
[info]   jstackdepth=<frames>             Maximum Java stack depth
[info]   minwidth=<pixels>                skip frames smaller than px
[info]   reverse=<bool>                   generate stack-reversed FlameGraph / Call tree
[info]   sig=<bool>                       Print method signatures
[info]   simple=<bool>                    Simple class names instead of FQN
[info]   threads=<int>                    Profile threads separately
[info]   title=<string>                   SVG title
[info]   traces=<int>                     Number of top traces to include in the default output
[info]                                    (default: [200])
[info]   verbose=<bool>                   Output the sequence of commands (default: [false])
[info]   width=<pixels>                   SVG width
```

## Generate textual output:

```
-prof "async:traces=2;flat=10"
...
[info] Secondary result "scala.tools.nsc.HotScalacBenchmark.compile:··async":
[info] --- Execution profile ---
[info] Total samples       : 6676
[info] unknown_Java        : 30 (0.45%)
[info] deoptimization      : 1 (0.01%)
[info] Frame buffer usage  : 27.8018%
[info] --- 1130000000 ns (1.69%), 113 samples
[info]   [ 0] PhaseChaitin::Split(unsigned int, ResourceArea*)
[info]   [ 1] PhaseChaitin::Register_Allocate()
[info]   [ 2] Compile::Code_Gen()
[info]   [ 3] Compile::Compile(ciEnv*, C2Compiler*, ciMethod*, int, bool, bool, bool, DirectiveSet*)
[info]   [ 4] C2Compiler::compile_method(ciEnv*, ciMethod*, int, DirectiveSet*)
[info]   [ 5] CompileBroker::invoke_compiler_on_method(CompileTask*)
[info]   [ 6] CompileBroker::compiler_thread_loop()
[info]   [ 7] JavaThread::thread_main_inner()
[info]   [ 8] JavaThread::run()
[info]   [ 9] Thread::call_run()
[info]   [10] thread_native_entry(Thread*)
[info]   [11] _pthread_start
[info]   [12] thread_start
[info] --- 860000000 ns (1.29%), 86 samples
[info]   [ 0] PhaseChaitin::elide_copy(Node*, int, Block*, Node_List&, Node_List&, bool)
[info]   [ 1] PhaseChaitin::post_allocate_copy_removal()
[info]   [ 2] PhaseChaitin::Register_Allocate()
[info]   [ 3] Compile::Code_Gen()
[info]   [ 4] Compile::Compile(ciEnv*, C2Compiler*, ciMethod*, int, bool, bool, bool, DirectiveSet*)
[info]   [ 5] C2Compiler::compile_method(ciEnv*, ciMethod*, int, DirectiveSet*)
[info]   [ 6] CompileBroker::invoke_compiler_on_method(CompileTask*)
[info]   [ 7] CompileBroker::compiler_thread_loop()
[info]   [ 8] JavaThread::thread_main_inner()
[info]   [ 9] JavaThread::run()
[info]   [10] Thread::call_run()
[info]   [11] thread_native_entry(Thread*)
[info]   [12] _pthread_start
[info]   [13] thread_start
[info]           ns  percent  samples  top
[info]   ----------  -------  -------  ---
[info]   1130000000    1.69%      113  PhaseChaitin::Split(unsigned int, ResourceArea*)
[info]   1120000000    1.68%      112  IndexSetIterator::advance_and_next()
[info]   1040000000    1.56%      104  Node::in(unsigned int) const
[info]    890000000    1.33%       89  IndexSet::insert(unsigned int)
[info]    860000000    1.29%       86  PhaseChaitin::elide_copy(Node*, int, Block*, Node_List&, Node_List&, bool)
[info]    790000000    1.18%       79  _platform_bzero$VARIANT$Haswell
[info]    730000000    1.09%       73  IndexSetIterator::next()
[info]    720000000    1.08%       72  __psynch_cvwait
[info]    690000000    1.03%       69  PhaseLive::compute(unsigned int)
[info]    680000000    1.02%       68  PhaseChaitin::post_allocate_copy_removal()
[info] # Run complete. Total time: 00:00:22
[info] REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
[info] why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
[info] experiments, perform baseline and negative tests that provide experimental control, make sure
[info] the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
[info] Do not assume the numbers tell you what you want them to tell.
[info] Benchmark                                   (corpusPath)  (corpusVersion)  (extraArgs)  (resident)  (scalaVersion)  (source)    Mode  Cnt     Score      Error  Units
[info] HotScalacBenchmark.compile                     ../corpus          a8c43dc                    false         2.12.12    scalap  sample    6  1821.726 ± 1159.498  ms/op
[info] HotScalacBenchmark.compile:compile·p0.00       ../corpus          a8c43dc                    false         2.12.12    scalap  sample       1453.326             ms/op
[info] HotScalacBenchmark.compile:compile·p0.50       ../corpus          a8c43dc                    false         2.12.12    scalap  sample       1754.268             ms/op
[info] HotScalacBenchmark.compile:compile·p0.90       ../corpus          a8c43dc                    false         2.12.12    scalap  sample       2579.497             ms/op
[info] HotScalacBenchmark.compile:compile·p0.95       ../corpus          a8c43dc                    false         2.12.12    scalap  sample       2579.497             ms/op
[info] HotScalacBenchmark.compile:compile·p0.99       ../corpus          a8c43dc                    false         2.12.12    scalap  sample       2579.497             ms/op
[info] HotScalacBenchmark.compile:compile·p0.999      ../corpus          a8c43dc                    false         2.12.12    scalap  sample       2579.497             ms/op
[info] HotScalacBenchmark.compile:compile·p0.9999     ../corpus          a8c43dc                    false         2.12.12    scalap  sample       2579.497             ms/op
[info] HotScalacBenchmark.compile:compile·p1.00       ../corpus          a8c43dc                    false         2.12.12    scalap  sample       2579.497             ms/op
[info] HotScalacBenchmark.compile:·async              ../corpus          a8c43dc                    false         2.12.12    scalap  sample            NaN               ---
```

## Generate Flamegraph

```
-prof "async:file=/tmp/flame.svg;minwidth=2"
```

## Generate Java Flight Recorder output for allocations

```
-prof "async:file=/tmp/prof.jfr;event=alloc"
```

WIP for #1

### CODE REVIEW

**Comment by apangin** [comment]
Hi Jason,
I'd love to see jmh native support for async-profiler, and I appreciate your work on that.
Here are some of my thoughts on the topic.

Since async-profiler works in the context of the JVM process, I think it's closer to `InternalProfiler` rather than an external tool. It has Java API, and this is the fastest way to interact with the profiler.

- Java API has methods to stop and resume profiling. This is a convenient way to profile only measurement iterations, skipping `@Setup`, `@TearDown` and all the auxiliary stuff.
- Results can be obtained directly from the native library without need to save and parse the output file.
- `System.loadLibrary` will load profiler from the stadard library path or from the directory specified with `-Djava.library.path`.

As to options parser, I'd probably skip all the processing in JMH, and pass the entire options string directly to the profiler.

- On one hand, the syntax won't be consistent with other profilers, but...
- On the other hand, this will eliminate the confusion between using the profiler standalone and inside jmh.
- There will be no need to replicate all profiler options in jmh, to care about option types, correctness etc. Everything will be checked just once in the profiler.
- This will be compatible with any version of async-profiler, new profiling options will be automatically available.

Right now I'm developing new major version of the async-profiler, which will have some conceptual changes. For example, it will collect multiple events together (cpu+alloc+lock), it will have unlimited frame buffer (the corresponding option will be removed). I anticipate major changes in how the different output formats will be processed, but there will be at least JFR compatible format. So, I wouldn't recommend hard-coding the existing async-profiler options in JMH now.

**Comment by retronym** [comment]
Thanks for your thoughts, @apangin!

I look forward to the new capabilities you are working on.  Do you foresee changes to the Java API?

I believe you are aware that I have an existing integration of JMH and async-profiler over in https://github.com/ktoso/sbt-jmh/blob/master/extras/src/main/java/pl/project13/scala/jmh/extras/profiler/AsyncProfiler.java.

In that version, I used `ExternalProfiler` to automatically add the recommended `-XX:+DebugNonSafePoints` JVM option, but also used  `InternalProfiler` to exclude warmup (although not setup/teardown) from the profile. That happens to use `jattach` to load and later control the profiler.

I was going for a more minimal approach in the upstream contribution which aligns with the way that other built in profiler integrations are implemented in JMH. I personally like excluding warmup though and doing so is particularly useful for async-profiler when evaluating JIT overhead in the steady state.

To switch to using the Java API, I need to find a way to call it from JMH. 
  - Direct use is tricky because the JAR is not currently published to Maven (https://github.com/jvm-profiling-tools/async-profiler/issues/93). 
   - I could include a copy of the sources (repackaged would be okay since https://github.com/jvm-profiling-tools/async-profiler/commit/837322439584a6a6eef11925b62379240ea150cd) in the JMH sources. I suppose this would require you to contribute them under an OCA. Keeping them in sync with new versions of async-profiler would require some ongoing work.
  - I could interact with it via reflection and require the user to add `$ASYNC_PROFILER_HOME/build/async-profiler.jar` to the classpath.
  - I could retarget this entire change to jvm-profiling-tools/async-profiler. You [declined that suggestion](https://github.com/jvm-profiling-tools/async-profiler/issues/76#issuecomment-368335698) previously, maybe you could reconsider? JMH is so widely used that it seems worth building a rich integration but the maintainers of JMH would be rightly wary of the maintenance burden implied by the solutions above and by the "exclude warmup" feature.

**Comment by retronym** [comment]
Here's working [draft](https://github.com/retronym/async-profiler/pull/1) of the alternative version which:
  - Uses the Java API to attach and control the profiler
  - Skips collection during warmup
  - Supports multiple output formats from one run
  - Is integrated with async-profiler, rather than with JMH, to ensure it stays up to date with changes in the profiling API

After trying both homes for the profiler and weighing up the tradeoffs, this is my preferred version.

**Comment by apangin** [comment]
> To switch to using the Java API, I need to find a way to call it from JMH.
> 
> * Direct use is tricky because the JAR is not currently published to Maven

Using async-profiler Java API is much simpler. No JAR dependencies. No need to copy anything from async-profiler sources (call it "zero-copy" technique :-)

You just need to add a couple of native methods to whatever Java class and call `System.loadLibrary`. async-profiler agent detects where `loadLibrary` or `load` is called from and automatically binds itself to the native methods of that class.

It's enough to define just 3 methods:
```java
    native void start0(String event, long interval, boolean reset) throws IllegalStateException;
    native void stop0() throws IllegalStateException;
    native String execute0(String command) throws IllegalArgumentException, IOException;
```

I haven't finalized Java API of async-profiler 2.0 yet, but most likely the above three methods will remain. `execute0` is the most universal one, as it passes an arbitrary command line string directly to the agent without preprocessing, and returns the raw output as well.

**Comment by apangin** [comment]
I still think that jmh repo is a better place for integration.

async-profiler project currently has no third party dependencies, except for the standard build tools. But it's not possible to add JMH profiler without dependency on JMH. At the same time, as I've shown above, adding async-profiler support in JMH requires no additional library dependencies.

It will be also more convenient from end user perspective. User will just specify `-prof` option, and that's it. JMH will automatically find and load async-profiler native library (which is going to be installed to the standard OS library path), everything else will be built into JMH. In contrast, when JMH integration is a part of async-profiler project, it will require user to specify path to async-profiler jar.

**Comment by retronym** [comment]
Submitted to jmh-dev: https://mail.openjdk.java.net/pipermail/jmh-dev/2020-August/002966.html

**Pull request closed without merging**
